DROP TABLE IF EXISTS usar_registration;

CREATE TABLE usar_registration
(
    member_id                           int PRIMARY KEY,
    rugby_union                         varchar(50) NOT NULL,
    club                                varchar(50) NOT NULL,
    first_name                          varchar(50) NOT NULL,
    last_name                           varchar(50) NOT NULL,
    gender                              varchar(6)  NOT NULL,
    dob                                 date        NOT NULL,
    status                              varchar(20) NOT NULL,
    registration_date                   timestamp   NOT NULL,
    address_1                           varchar(50) NOT NULL,
    address_2                           varchar(50),
    city                                varchar(25) NOT NULL,
    province                            varchar(25) NOT NULL,
    country                             varchar(25) NOT NULL,
    postal_code                         varchar(25) NOT NULL,
    email                               varchar(50) NOT NULL,
    phone_number                        varchar(20) NOT NULL,
    emergency_name                      varchar(50),
    emergency_phone_number              varchar(20),
    parent_guardian_name                varchar(50),
    parent_guardian_email               varchar(50),
    parent_guardian_phone_number        varchar(20),
    second_parent_guardian_name         varchar(50),
    second_parent_guardian_email        varchar(50),
    second_parent_guardian_phone_number varchar(20),
    school_name                         varchar(50),
    membership_package                  varchar(50) NOT NULL,
    membership_types                    varchar(50) NOT NULL,
    club_categories                     varchar(50) NOT NULL,
    province_categories                 varchar(50) NOT NULL,
    association_categories              varchar(50) NOT NULL,
    sort_dob                            date        NOT NULL,
    start_date                          date,
    expiry_date                         date        NOT NULL,
    second_member_id                    int         NOT NULL
);